list=['ali','atefeh','reza','homa','amir','fatemeh']
aqazade1=input("what is your name? ")
p1=int(input('where do you want to be?'))
aqazade2=input("what is your name? ")
p2=int(input('where do you want to be?'))
aqazade3=input("what is your name?  ")
p3=int(input('where do you want to be?'))
list.insert(p1-1,aqazade1)
list.insert(p2-1,aqazade2)
list.insert(p3-1,aqazade3)
print('final list : ',list)